name = "syxpher"
main = "worker.js"
compatibility_date = "2026-08-05"

[assets]
directory = "./assets"

[[d1_databases]]
binding = "DB"
database_name = "site-db"
database_id = "544b1188-eaa7-4302-abec-d8ecca1afb9e"
